### ISSUE TITLE
ValueError: 'HYBRID' is not a valid DriveTrainType

### ISSUE THREAD

**Issue by juraurban** [bimmerconnected/ha_custom_component#10]
I have 2021 M440i: After installation of the latest beta there is issue with:
Logger: homeassistant.components.lock
Source: custom_components/bmw_connected_drive/lock.py:59
Integration: Lock (documentation, issues)
First occurred: 8:42:03 PM (1 occurrences)
Last logged: 8:42:03 PM

Error while setting up bmw_connected_drive platform for lock
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/bmw_connected_drive/lock.py", line 35, in async_setup_entry
entities = [
File "/config/custom_components/bmw_connected_drive/lock.py", line 36, in 
BMWLock(account, vehicle, "lock", "BMW lock")
File "/config/custom_components/bmw_connected_drive/lock.py", line 59, in init
self.door_lock_state_available = DOOR_LOCK_STATE in vehicle.available_attributes
File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 172, in available_attributes
result += self.drive_train_attributes
File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 149, in drive_train_attributes
if self.has_hv_battery:
File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 118, in has_hv_battery
return self.drive_train in HV_BATTERY_DRIVE_TRAINS
File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 100, in drive_train
return DriveTrainType(self.attributes['driveTrain'])
File "/usr/local/lib/python3.9/enum.py", line 384, in call
return cls.new(cls, value)
File "/usr/local/lib/python3.9/enum.py", line 702, in new
raise ve_exc
ValueError: 'HYBRID' is not a valid DriveTrainType

Logger: homeassistant.components.sensor
Source: custom_components/bmw_connected_drive/sensor.py:143 
Integration: Sensor (documentation, issues) 
First occurred: 8:42:03 PM (1 occurrences) 
Last logged: 8:42:03 PM

Error while setting up bmw_connected_drive platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bmw_connected_drive/sensor.py", line 143, in async_setup_entry
    for attribute_name in vehicle.drive_train_attributes
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 149, in drive_train_attributes
    if self.has_hv_battery:
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 118, in has_hv_battery
    return self.drive_train in HV_BATTERY_DRIVE_TRAINS
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 100, in drive_train
    return DriveTrainType(self.attributes['driveTrain'])
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'HYBRID' is not a valid DriveTrainType

**Comment by rikroe** [comment]
Thanks! I'll integrate it into the library!

**Comment by rikroe** [comment]
Should be fixed since a couple of days, please try again with the lastest custom component/library.
