### ISSUE TITLE
401 Unauthorized errora from beta component using rest_of_world region

### ISSUE THREAD

**Issue by Djelibeybi** [bimmerconnected/ha_custom_component#11]
Hey folks,

I'm getting the following error when Home Assistant starts, but not every time. I haven't yet determined how to reproduce it reliably:

```bash
Logger: bimmer_connected.account
Source: /usr/local/lib/python3.9/site-packages/bimmer_connected/account.py:231
First occurred: 9:42:11 AM (1 occurrences)
Last logged: 9:42:11 AM
401 Client Error: Unauthorized for url: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=660.0&appDateTime=1637408530.215427&tireGuardMode=ENABLED

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 229, in send_request
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=660.0&appDateTime=1637408530.215427&tireGuardMode=ENABLED
```

**Comment by rikroe** [comment]
Thanks for the report!

Could you please set the loggers to debug to see what happens before?

```yaml
logger:
  default: info
  logs:
    homeassistant.components.bmw_connected_drive: debug
    custom_components.bmw_connected_drive: debug
    bimmer_connected: debug
```

**Comment by Djelibeybi** [comment]
Will do.

**Comment by rikroe** [comment]
I've seen the issue by myself today, looks like a timing issue. 
It seems that the authentication token already expired on the server side but by our calculation it would still be valid for a second or two.

That's a quite easy fix, will let you know once it is integrated.
