### ISSUE TITLE
Integration does not load after HA restart

### ISSUE THREAD

**Issue by uphillbattle** [bimmerconnected/ha_custom_component#15]
Using 

- HACS 1.18.0 (just updated this morning and then restarted HA to load the new version)

- BMW Connected Drive BETA version 20211127.1

The BMW integration does not load and I get this error message
```
Logger: bimmer_connected.account
Source: /usr/local/lib/python3.9/site-packages/bimmer_connected/account.py:302
First occurred: 08:39:50 (1 occurrences)
Last logged: 08:39:50

502 Server Error: ID Lookup Service Timeout for url: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638167960.294904&tireGuardMode=ENABLED
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 300, in send_request
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: ID Lookup Service Timeout for url: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638167960.294904&tireGuardMode=ENABLED
```

Maybe something at the BMW end?

**Comment by uphillbattle** [comment]
Never mind. Evidently, it was a problem at the BMW end, because the problem was solved automagically.
