### ISSUE TITLE
New errors in log

### ISSUE THREAD

**Issue by Pirol62** [bimmerconnected/ha_custom_component#16]
Hi, since a few days I have the following error in my log:
````
Logger: custom_components.bmw_connected_drive
Source: custom_components/bmw_connected_drive/__init__.py:319
Integration: BMW Connected Drive
First occurred: 11:50:35 (2 occurrences)
Last logged: 12:30:36

404 Client Error: Not Found for url: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638265835.878114&tireGuardMode=ENABLED
404 Client Error: Not Found for url: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638268236.338436&tireGuardMode=ENABLED
Traceback (most recent call last):
  File "/config/custom_components/bmw_connected_drive/__init__.py", line 319, in update
    self.account.update_vehicle_states()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 412, in update_vehicle_states
    self._get_vehicles()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 376, in _get_vehicles
    response = self.send_request(
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 303, in send_request
    raise ex
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 300, in send_request
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638265835.878114&tireGuardMode=ENABLED
````
````
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.bmw_connected_drive
Source: custom_components/bmw_connected_drive/__init__.py:323
Integration: BMW Connected Drive
First occurred: 11:50:35 (2 occurrences)
Last logged: 12:30:36

Could not connect to the BMW Connected Drive portal. The vehicle state could not be updated
````
````
Logger: bimmer_connected.account
Source: /usr/local/lib/python3.9/site-packages/bimmer_connected/account.py:302
First occurred: 11:50:35 (2 occurrences)
Last logged: 12:30:36

404 Client Error: Not Found for url: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638265835.878114&tireGuardMode=ENABLED
404 Client Error: Not Found for url: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638268236.338436&tireGuardMode=ENABLED
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 300, in send_request
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cocoapi.bmwgroup.com/eadrax-vcs/v1/vehicles?apptimezone=60.0&appDateTime=1638265835.878114&tireGuardMode=ENABLED
````

**Comment by rikroe** [comment]
Please let me know if there is any additional information with the additional logging of the custom component.

**Comment by Pirol62** [comment]
The error never appeared again. Let's close this and reopen in case of reappearing.
