### ISSUE TITLE
a lot of authentication errors in log

### ISSUE THREAD

**Issue by Pirol62** [bimmerconnected/ha_custom_component#27]
HA OS: 2021.11.5
Connected Drive Verion: latest

Error:
````
Logger: bimmer_connected.account
Source: /usr/local/lib/python3.9/site-packages/bimmer_connected/account.py:217
First occurred: 14:29:24 (3 occurrences)
Last logged: 14:30:09

Authentication failed (invalid_client): Client authentication failed (e.g., login failure, unknown client, no client authentication included or unsupported authentication method)
Logger: bimmer_connected.account
Source: /usr/local/lib/python3.9/site-packages/bimmer_connected/account.py:107
First occurred: 14:29:24 (3 occurrences)
Last logged: 14:30:09

------------

401 Client Error: Unauthorized for url: https://customer.bmwgroup.com/gcdm/oauth/authenticate
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 94, in _get_oauth_token
    token_data = self._login_row_na()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 220, in _login_row_na
    raise ex
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 170, in _login_row_na
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://customer.bmwgroup.com/gcdm/oauth/authenticate
````

The entities are available and provide values

**Comment by rikroe** [comment]
20211211.1 should still be working, although it is spamming the log with error messages (issue on BMW side). 
There will be a `bimmer_connected==0.8.9` shortly (check the library repo), which you could try to set manually in `custom_components/bmw_connected_drive/manifest.json`. 

That should get rid of the authentication issues but you would still be compatible with HA 2021.11.

**Comment by Pirol62** [comment]
The authentication error is gone or very seldom even on 2021.11.5. Close this.
