### ISSUE TITLE
not able login

### ISSUE THREAD

**Issue by Bit-Bag** [bimmerconnected/ha_custom_component#32]
Logger: bimmer_connected.account
Source: /usr/local/lib/python3.9/site-packages/bimmer_connected/account.py:112 
First occurred: 11:17:18 (2 occurrences) 
Last logged: 11:27:13

422 Client Error: Unprocessable Entity for url: https://myprofile.bmw.com.cn/eadrax-coas/v1/login/pwd
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 101, in _get_oauth_token
    token_data = self._login_china()
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 271, in _login_china
    raise ex
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 252, in _login_china
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://myprofile.bmw.com.cn/eadrax-coas/v1/login/pwd

docker ,home assistant 2022.2.9 with the master bimmerconnected
can you help me ?

**Comment by rikroe** [comment]
Sorry, totally missed this. This still an issue? It at least works with my test account (without any vehicles).

**Comment by rikroe** [comment]
Fixed at latest with the current custom component / will be included in HA 2022.6
