### ISSUE TITLE
AttributeError: 'FuelAndBattery' object has no attribute 'charging_time_label'

### ISSUE THREAD

**Issue by ToranBrown** [bimmerconnected/ha_custom_component#53]
I'm currently seeing the following error showing up in the HA Logs:

Logger: homeassistant.components.sensor
Source: custom_components/bmw_connected_drive/sensor.py:197
Integration: Sensor (documentation, issues)
First occurred: 12:55:12 PM (2 occurrences)
Last logged: 12:55:12 PM

Error adding entities for domain sensor with platform bmw_connected_drive
Error while setting up bmw_connected_drive platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 673, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 775, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/bmw_connected_drive/__init__.py", line 191, in async_added_to_hass
    self._handle_coordinator_update()
  File "/config/custom_components/bmw_connected_drive/sensor.py", line 197, in _handle_coordinator_update
    state = getattr(
AttributeError: 'FuelAndBattery' object has no attribute 'charging_time_label'

This error occurs on both the current BMW Connected Drive Production version as well as the BMW Connected Drive BETA version 20220716.1

**Comment by rikroe** [comment]
Fixed in the latest custom component and will be included in 2022.9
