### ISSUE TITLE
AttributeError: can't set attribute 'targets'

### ISSUE THREAD

**Issue by geertge** [bimmerconnected/ha_custom_component#58]
When I implement this ha_custom_component for my Ev I get the following error:

Logger: homeassistant.components.notify
Source: custom_components/bmw_connected_drive/notify.py:57
Integration: Meldingen (documentation, issues)
First occurred: 09:05:43 (1 occurrences)
Last logged: 09:05:43

Error setting up platform bmw_connected_drive
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/notify/legacy.py", line 93, in async_setup_platform
    notify_service = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bmw_connected_drive/notify.py", line 49, in get_service
    return BMWNotificationService(targets)
  File "/config/custom_components/bmw_connected_drive/notify.py", line 57, in __init__
    self.targets: dict[str, MyBMWVehicle] = targets
AttributeError: can't set attribute 'targets'

Can I fix this porblem?

**Comment by gerard33** [comment]
There was still an old version of `notify.py` in the release. Should have been fixed now.
Can you try it with the latest [version](https://github.com/bimmerconnected/ha_custom_component/releases/tag/20230315.1)?

**Comment by geertge** [comment]
Thanks, it's now working.
