### ISSUE TITLE
Error: unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by jmcollin78** [bimmerconnected/ha_custom_component#67]
Hello, since the update in 20230604.1, I always get this error :

```
Unable to prepare setup for platform bmw_connected_drive.number: Platform not found (Exception importing custom_components.bmw_connected_drive.number).
```

In logs, I can see this:

```
2023-06-07 20:18:21.893 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.bmw_connected_drive.number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/bmw_connected_drive/number.py", line 46, in <module>
    BMWNumberEntityDescription(
TypeError: BMWNumberEntityDescription.__init__() got an unexpected keyword argument 'mode'
```

Any clues to what happens ?

**Comment by rikroe** [comment]
Mhh, could be that HA 2021.6 is required or I missed something when copying to the custom component.
I won't find much time in the next days though.

**Comment by rikroe** [comment]
Got some unexpected time this morning. There were additional changes to the HA component I wasn't aware of and I have implemented a workaround in the latest custom component (20230608.1) - although if you're migrating to HA 2023.6 soon, you can also remove the custom component as all functionality is included in HA core.

**Comment by jmcollin78** [comment]
Clear thank tout !

**Comment by jmcollin78** [comment]
Works fine with the official integration and HA 2023.6.1
