### ISSUE TITLE
all entities turns to unavailable

### ISSUE THREAD

**Issue by dengke80622** [bimmerconnected/ha_custom_component#68]
Description: 
All BMW entities become unavailable and become normal after a while. 
Reload integration can temporarily solve this issue but will be "unavailable" again after a while.
Seems there is some update interval for this, 5 or 10 minutes in the screenshot
![image](https://github.com/home-assistant/home-assistant.io/assets/16779356/76a59d61-7b70-403f-ae32-8ad9f003a7e9)
![image](https://github.com/home-assistant/home-assistant.io/assets/16779356/215ebf9d-6d79-4f67-8627-ebe839d536e6)
![image](https://github.com/home-assistant/home-assistant.io/assets/16779356/3a297098-31f2-415a-b970-f43ff7a9a19f)

LOG:
This error originated from a custom integration.

Logger: custom_components.bmw_connected_drive.coordinator
Source: custom_components/bmw_connected_drive/coordinator.py:61
Integration: BMW Connected Drive
First occurred: 14:24:13 (3 occurrences)
Last logged: 14:49:17

Unexpected error fetching bmw_connected_drive-86[PHONE#] data: 'capabilities'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bmw_connected_drive/coordinator.py", line 61, in _async_update_data
    await self.account.get_vehicles()
  File "/usr/local/lib/python3.11/site-packages/bimmer_connected/account.py", line 113, in get_vehicles
    if vehicle_state[ATTR_CAPABILITIES].get("isChargingPlanSupported", False) or vehicle_state[
       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'capabilities'


### Additional information

Home Assistant 2023.6.2
Supervisor 2023.06.2
Operating System 10.2
Frontend 20230608.0 - latest

**Comment by dengke80622** [comment]
In testing, downgrade core to 2023.5.4, test 20230608.1 from HACS

**Comment by dengke80622** [comment]
new issue, cannot log in
![image](https://github.com/bimmerconnected/ha_custom_component/assets/16779356/7fbd06b6-9834-47af-920b-19ede6d364e4)

```
Logger: bimmer_connected.api.authentication
Source: custom_components/bmw_connected_drive/config_flow.py:44
Integration: BMW Connected Drive
First occurred: June 28, 2023 at 11:37:45 (14 occurrences)
Last logged: 15:56:06

MyBMW API error: HTTPStatusError: True -
```

**Comment by rikroe** [comment]
BMW seems to have adjusted something on their API. Unfortunately I'm very constrained on time right now.
@Yixi have you noticed some API changes as well?

**Comment by Yixi** [comment]
Yes, I have the same issue. It intermittently becomes unavailable for about 5 minutes.

![image](https://github.com/bimmerconnected/ha_custom_component/assets/1411722/a30cf810-b16a-43f6-9bb2-5c0805a0cf81)

In history, the transparent black portion indicates unavailability

I haven't had time in the past few days to research the reason why, but it seems like it has returned to normal since yesterday.

**Comment by dengke80622** [comment]
pull the latest integration into custom components, shown below 
![image](https://github.com/bimmerconnected/ha_custom_component/assets/16779356/8e4af312-a413-4a41-8993-7b94320365dc)
logs:
![image](https://github.com/bimmerconnected/ha_custom_component/assets/16779356/45c997c8-a28d-4fe0-ad97-835219878aa2)

**Comment by Yixi** [comment]
![image](https://github.com/bimmerconnected/ha_custom_component/assets/1411722/ef0fb716-d1de-4178-8973-94f3244ac83b)

It seems that logging into the China region is still functional. Could you please check your username and password?

**Comment by dengke80622** [comment]
login again with bmw app, it said my account has been blocked...
Reset password and integration works again.
![image](https://github.com/bimmerconnected/ha_custom_component/assets/16779356/eecefa78-e88d-41be-8c70-e720581a8680)

Append debug info for your ref.
```
vm@ubuntu:~$ /home/vm/.local/bin/bimmerconnected fingerprint 8613300000000 PASSWORD china
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:bimmer_connected.account:Getting vehicle list
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/etc/ssl/certs/ca-certificates.crt'
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/etc/ssl/certs/ca-certificates.crt'
DEBUG:bimmer_connected.api.authentication:Authenticating with MyBMW flow for China.
DEBUG:httpcore.connection:connect_tcp.started host='myprofile.bmw.com.cn' port=443 local_address=None timeout=30.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7f3336eb81f0>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x7f3336f50740> server_hostname='myprofile.bmw.com.cn' timeout=30.0
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x7f3336f050a0>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Tue, 11 Jul 2023 03:33:25 GMT'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'356'), (b'Connection', b'keep-alive'), (b'x-correlation-id', b'de9ae38331a9e72d7a8b15d2b6c6f7a2'), (b'x-cluster-mock-used', b'false'), (b'Request-Context', b'appId=cid-v1:371a0a96-89bf-40b1-b661-0d19eb534873')])
INFO:httpx:HTTP Request: GET https://myprofile.bmw.com.cn/eadrax-coas/v1/cop/publickey "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'GET']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 201, b'Created', [(b'Date', b'Tue, 11 Jul 2023 03:33:26 GMT'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'75751'), (b'Connection', b'keep-alive'), (b'x-correlation-id', b'84bb7b3abbd653d72e1b3b539cc0f47f'), (b'x-cluster-mock-used', b'false'), (b'Request-Context', b'appId=cid-v1:371a0a96-89bf-40b1-b661-0d19eb534873')])
INFO:httpx:HTTP Request: POST https://myprofile.bmw.com.cn/eadrax-coas/v2/cop/slider-captcha "HTTP/1.1 201 Created"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 201, b'Created', [(b'Date', b'Tue, 11 Jul 2023 03:33:26 GMT'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'57'), (b'Connection', b'keep-alive'), (b'x-correlation-id', b'4244d71fcb2f8a3f299d8bfa55d640e1'), (b'x-cluster-mock-used', b'false'), (b'Request-Context', b'appId=cid-v1:371a0a96-89bf-40b1-b661-0d19eb534873')])
INFO:httpx:HTTP Request: POST https://myprofile.bmw.com.cn/eadrax-coas/v1/cop/check-captcha "HTTP/1.1 201 Created"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 422, b'Unprocessable Entity', [(b'Date', b'Tue, 11 Jul 2023 03:33:26 GMT'), (b'Content-Type', b'application/json; charset=utf-8'), (b'Content-Length', b'165'), (b'Connection', b'keep-alive'), (b'x-correlation-id', b'36de83a33d312413a2b174505c137fee'), (b'x-cluster-mock-used', b'false'), (b'Request-Context', b'appId=cid-v1:371a0a96-89bf-40b1-b661-0d19eb534873')])
INFO:httpx:HTTP Request: POST https://myprofile.bmw.com.cn/eadrax-coas/v2/login/pwd "HTTP/1.1 422 Unprocessable Entity"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
DEBUG:httpcore.http11:response_closed.complete
ERROR:bimmer_connected.api.authentication:MyBMWAPIError due to HTTPStatusError: True - 
DEBUG:httpcore.connection:close.started
DEBUG:httpcore.connection:close.complete
Traceback (most recent call last):
  File "/home/dengke/.local/lib/python3.8/site-packages/bimmer_connected/api/authentication.py", line 383, in raise_for_status_event_handler
    response.raise_for_status()
  File "/home/dengke/.local/lib/python3.8/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://myprofile.bmw.com.cn/eadrax-coas/v2/login/pwd'
For more information check: https://httpstatuses.com/422

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dengke/.local/bin/bimmerconnected", line 8, in <module>
    sys.exit(main())
  File "/home/dengke/.local/lib/python3.8/site-packages/bimmer_connected/cli.py", line 356, in main
    loop.run_until_complete(args.func(args))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dengke/.local/lib/python3.8/site-packages/bimmer_connected/cli.py", line 175, in fingerprint
    await account.get_vehicles()
  File "/home/dengke/.local/lib/python3.8/site-packages/bimmer_connected/account.py", line 93, in get_vehicles
    await self._init_vehicles()
  File "/home/dengke/.local/lib/python3.8/site-packages/bimmer_connected/account.py", line 72, in _init_vehicles
    vehicles_responses: List[httpx.Response] = [
  File "/home/dengke/.local/lib/python3.8/site-packages/bimmer_connected/account.py", line 73, in <listcomp>
    await client.get(
  File "/home/dengke/.local/lib/python3.8/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
  File "/home/dengke/.local/lib/python3.8/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/dengke/.local/lib/python3.8/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/home/dengke/.local/lib/python3.8/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    request = await auth_flow.__anext__()
  File "/home/dengke/.local/lib/python3.8/site-packages/bimmer_connected/api/authentication.py", line 80, in async_auth_flow
    await self.login()
  File "/home/dengke/.local/lib/python3.8/site-packages/bimmer_connected/api/authentication.py", line 129, in login
    token_data = await self._login_china()
  File "/home/dengke/.local/lib/python3.8/site-packages/bimmer_connected/api/authentication.py", line 299, in _login_china
    response = await client.post(
  File "/home/dengke/.local/lib/python3.8/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/home/dengke/.local/lib/python3.8/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/dengke/.local/lib/python3.8/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/home/dengke/.local/lib/python3.8/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/dengke/.local/lib/python3.8/site-packages/httpx/_client.py", line 1703, in _send_handling_redirects
    raise exc
  File "/home/dengke/.local/lib/python3.8/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    await hook(response)
  File "/home/dengke/.local/lib/python3.8/site-packages/bimmer_connected/api/authentication.py", line 385, in raise_for_status_event_handler
    await handle_httpstatuserror(ex, log_handler=_LOGGER)
  File "/home/dengke/.local/lib/python3.8/site-packages/bimmer_connected/api/utils.py", line 83, in handle_httpstatuserror
    raise _ex_to_raise(_err_message) from ex
bimmer_connected.models.MyBMWAPIError: HTTPStatusError: True - 

```
