### ISSUE TITLE
NOT_SUPPORTED is not a valid lsc type

### ISSUE THREAD

**Issue by VVlasy** [bimmerconnected/ha_custom_component#8]
Hi,

I have a 2016 440i bmw and I am getting this error even on the latest beta (I was also getting this on older betas. Installed vis HACS

1)
`Logger: homeassistant.components.sensor
Source: custom_components/bmw_connected_drive/sensor.py:144 
Integration: Senzor (documentation, issues) 
First occurred: 22:17:20 (1 occurrences) 
Last logged: 22:17:20

Error while setting up bmw_connected_drive platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bmw_connected_drive/sensor.py", line 139, in async_setup_entry
    [
  File "/config/custom_components/bmw_connected_drive/sensor.py", line 144, in <listcomp>
    if attribute_name in vehicle.available_attributes
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 170, in available_attributes
    if self.lsc_type == LscType.ACTIVATED:
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 163, in lsc_type
    return LscType(self.attributes["capabilities"]["lastStateCall"].get('lscState'))
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'NOT_SUPPORTED' is not a valid LscType`

2: 

Logger: homeassistant.components.lock
Source: custom_components/bmw_connected_drive/lock.py:59 
Integration: Zámek (documentation, issues) 
First occurred: 22:17:20 (1 occurrences) 
Last logged: 22:17:20

Error while setting up bmw_connected_drive platform for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bmw_connected_drive/lock.py", line 35, in async_setup_entry
    entities = [
  File "/config/custom_components/bmw_connected_drive/lock.py", line 36, in <listcomp>
    BMWLock(account, vehicle, "lock", "BMW lock")
  File "/config/custom_components/bmw_connected_drive/lock.py", line 59, in __init__
    self.door_lock_state_available = DOOR_LOCK_STATE in vehicle.available_attributes
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 170, in available_attributes
    if self.lsc_type == LscType.ACTIVATED:
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 163, in lsc_type
    return LscType(self.attributes["capabilities"]["lastStateCall"].get('lscState'))
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'NOT_SUPPORTED' is not a valid LscType

3: 
Logger: homeassistant.components.binary_sensor
Source: custom_components/bmw_connected_drive/binary_sensor.py:229 
Integration: Binární senzor (documentation, issues) 
First occurred: 22:17:19 (1 occurrences) 
Last logged: 22:17:19

Error while setting up bmw_connected_drive platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bmw_connected_drive/binary_sensor.py", line 225, in async_setup_entry
    entities = [
  File "/config/custom_components/bmw_connected_drive/binary_sensor.py", line 229, in <listcomp>
    if description.key in vehicle.available_attributes
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 170, in available_attributes
    if self.lsc_type == LscType.ACTIVATED:
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 163, in lsc_type
    return LscType(self.attributes["capabilities"]["lastStateCall"].get('lscState'))
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'NOT_SUPPORTED' is not a valid LscType

**Comment by VVlasy** [comment]
My car does not send back the status of locks, lights etc. But the commands can be executed. It is obviously the source of this error.

**Comment by rhoddan** [comment]
I have same problem that locks (haven’t tested more yet) is not sending back updates. I also tried to force the update via service command
BMW x330e

**Comment by VVlasy** [comment]
My car actually does not support sending back status. Only location can be received back from the car. But even that is not working

**Comment by rhoddan** [comment]
It worked in earlier version (for me)

**Comment by juraurban** [comment]
I have 2021 M440i: After installation of the latest beta there is issue with:
Logger: homeassistant.components.lock
Source: custom_components/bmw_connected_drive/lock.py:59 
Integration: Lock (documentation, issues) 
First occurred: 8:42:03 PM (1 occurrences) 
Last logged: 8:42:03 PM

Error while setting up bmw_connected_drive platform for lock
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bmw_connected_drive/lock.py", line 35, in async_setup_entry
    entities = [
  File "/config/custom_components/bmw_connected_drive/lock.py", line 36, in <listcomp>
    BMWLock(account, vehicle, "lock", "BMW lock")
  File "/config/custom_components/bmw_connected_drive/lock.py", line 59, in __init__
    self.door_lock_state_available = DOOR_LOCK_STATE in vehicle.available_attributes
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 172, in available_attributes
    result += self.drive_train_attributes
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 149, in drive_train_attributes
    if self.has_hv_battery:
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 118, in has_hv_battery
    return self.drive_train in HV_BATTERY_DRIVE_TRAINS
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 100, in drive_train
    return DriveTrainType(self.attributes['driveTrain'])
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'HYBRID' is not a valid DriveTrainType

**Comment by juraurban** [comment]
Logger: homeassistant.components.sensor
Source: custom_components/bmw_connected_drive/sensor.py:143 
Integration: Sensor (documentation, issues) 
First occurred: 8:42:03 PM (1 occurrences) 
Last logged: 8:42:03 PM

Error while setting up bmw_connected_drive platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bmw_connected_drive/sensor.py", line 143, in async_setup_entry
    for attribute_name in vehicle.drive_train_attributes
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 149, in drive_train_attributes
    if self.has_hv_battery:
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 118, in has_hv_battery
    return self.drive_train in HV_BATTERY_DRIVE_TRAINS
  File "/usr/local/lib/python3.9/site-packages/bimmer_connected/vehicle.py", line 100, in drive_train
    return DriveTrainType(self.attributes['driveTrain'])
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'HYBRID' is not a valid DriveTrainType

**Comment by rikroe** [comment]
Didn't keep an eye on the issues here, sorry. 
Should be already fixed since a couple of days, please try again with the lastest custom component/library.
